-- Thay đổi kiểu dữ liệu của các cột name và destination thành utf8mb4
ALTER TABLE activity_itineraries
    MODIFY time VARCHAR (255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    MODIFY activity_description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    MODIFY place VARCHAR (255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `activity_itineraries` (`activity_id`, `itiner_id`, `time`, `activity_description`, `place`)
VALUES (1, 1, '08h00', 'Khởi hành từ khách sạn', 'Khách sạn ABC'),
       (2, 1, '09h00', 'Tham quan di tích lịch sử', 'Di tích XYZ'),
       (3, 1, '12h00', 'Ăn trưa tại nhà hàng địa phương', 'Nhà hàng 123'),
       (4, 1, '14h00', 'Tham quan bảo tàng', 'Bảo tàng Quốc gia'),
       (5, 1, '16h00', 'Tham quan công viên', 'Công viên Thống Nhất'),
       (6, 2, '08h00', 'Khởi hành từ khách sạn', 'Khách sạn DEF'),
       (7, 2, '09h30', 'Tham quan vườn thú', 'Vườn thú ABC'),
       (8, 2, '12h30', 'Ăn trưa tại quán ăn địa phương', 'Quán ăn 456'),
       (9, 2, '15h00', 'Tham quan đền thờ', 'Đền thờ XYZ'),
       (10, 2, '18h00', 'Tiệc tối', 'Nhà hàng Sang trọng'),
       (11, 3, '07h30', 'Khởi hành từ khách sạn', 'Khách sạn GHI'),
       (12, 3, '09h00', 'Tham quan khu phố cổ', 'Phố cổ A'),
       (13, 3, '12h00', 'Ăn trưa tại nhà hàng nổi tiếng', 'Nhà hàng 789'),
       (14, 3, '14h00', 'Chụp ảnh tại điểm tham quan nổi tiếng', 'Điểm tham quan B'),
       (15, 3, '17h00', 'Tham gia hoạt động giải trí', 'Công viên giải trí C'),
       (16, 4, '08h00', 'Khởi hành từ khách sạn', 'Khách sạn JKL'),
       (17, 4, '09h00', 'Tham quan núi', 'Núi D'),
       (18, 4, '12h00', 'Ăn trưa tại nhà hàng núi', 'Nhà hàng M'),
       (19, 4, '14h30', 'Đi dạo quanh hồ', 'Hồ N'),
       (20, 4, '16h00', 'Tham gia hoạt động thể thao', 'Sân thể thao O'),
       (21, 5, '08h30', 'Khởi hành từ khách sạn', 'Khách sạn MNO'),
       (22, 5, '09h30', 'Tham quan khu di tích', 'Khu di tích P'),
       (23, 5, '12h30', 'Ăn trưa tại nhà hàng địa phương', 'Nhà hàng Q'),
       (24, 5, '15h00', 'Tham quan nhà máy sản xuất', 'Nhà máy R'),
       (25, 5, '18h00', 'Tiệc tối tại nhà hàng sang trọng', 'Nhà hàng S'),
       (26, 6, '08h00', 'Khởi hành từ khách sạn', 'Khách sạn TUV'),
       (27, 6, '09h30', 'Tham quan vườn hoa', 'Vườn hoa W'),
       (28, 6, '12h30', 'Ăn trưa tại quán cà phê', 'Quán cà phê X'),
       (29, 6, '15h00', 'Tham quan trung tâm thương mại', 'Trung tâm thương mại Y'),
       (30, 6, '19h00', 'Tham gia chương trình giải trí', 'Nhà hát Z'),
       (31, 7, '07h00', 'Khởi hành từ khách sạn', 'Khách sạn AA'),
       (32, 7, '09h00', 'Tham quan thắng cảnh', 'Thắng cảnh BB'),
       (33, 7, '12h00', 'Ăn trưa tại nhà hàng địa phương', 'Nhà hàng CC'),
       (34, 7, '14h00', 'Tham quan chợ địa phương', 'Chợ DD'),
       (35, 7, '16h00', 'Tham gia hoạt động thể thao', 'Sân thể thao EE'),
       (36, 8, '08h30', 'Khởi hành từ khách sạn', 'Khách sạn FF'),
       (37, 8, '09h30', 'Tham quan bảo tàng', 'Bảo tàng GG'),
       (38, 8, '12h30', 'Ăn trưa tại nhà hàng ven biển', 'Nhà hàng HH'),
       (39, 8, '15h00', 'Đi dạo trên bãi biển', 'Bãi biển II'),
       (40, 8, '18h00', 'Tiệc tối trên du thuyền', 'Du thuyền JJ'),
       (41, 9, '08h00', 'Khởi hành từ khách sạn', 'Khách sạn KK'),
       (42, 9, '09h30', 'Tham quan đồi chè', 'Đồi chè LL'),
       (43, 9, '12h30', 'Ăn trưa tại nhà hàng địa phương', 'Nhà hàng MM'),
       (44, 9, '15h00', 'Tham gia lớp học nấu ăn', 'Lớp học NN'),
       (45, 9, '17h00', 'Tham quan vườn trái cây', 'Vườn trái cây OO'),
       (46, 10, '08h00', 'Khởi hành từ khách sạn', 'Khách sạn PP'),
       (47, 10, '09h30', 'Tham quan khu vui chơi', 'Khu vui chơi QQ'),
       (48, 10, '12h00', 'Ăn trưa tại nhà hàng địa phương', 'Nhà hàng RR'),
       (49, 10, '14h00', 'Tham gia hoạt động văn hóa', 'Trung tâm văn hóa SS'),
       (50, 10, '17h00', 'Tham quan thắng cảnh', 'Thắng cảnh TT');

